const englishConstants = {
    ENTE: 'ente',
    FAMILY: 'Family',
    SHARING: 'Sharing',
    MEMBERS: 'Members',
    MEMBERS_LOWERCASE: 'members',
    INTRODUCING: 'Introducing',
    FAMILY_SHARING: 'Family Sharing',
    SHARE_YOUR_PLAN: 'Share your plan with your family members.',
    EACH_MEMBER_GETS_OWN_SPACE: 'Each member gets their own private space.',
    GET_STARTED: 'Get Started',
    INVITE_UPTO: 'You can invite upto',
    FAMILY_MANAGER: 'Family Manager',
    INVITE_YOUR_LOVED_ONES:
        'Invite your loved ones to share your storage plan.',
    BREAKDOWN: 'Breakdown',
    CONGRATULATIONS: 'Congratulations!',
    SUCCESSFULLY_JOINED: 'You have successfully joined',
    FAMILY_ON: "'s family on",
    YOU_NOW_HAVE_ACCESS: 'You now have access to',
    OF_SHARED_STORAGE: 'of shared storage.',
    PLEASE_OPEN_ENTE: 'Please open your',
    BACKUP_PHOTOS_AND_VIDEOS: 'app to backup photos and videos.',
    OPEN_ENTE: 'Open ente',
    ENTER_VALID_EMAIL: 'Please enter a valid email address',
    INVITE: 'Invite',
    INVITE_SENT: 'Invite sent',
    INVITE_MEMBER: 'Invite member',
    PRIVATE_SPACE: 'Private space will be allocated',
    DATA_NOT_SHARED: 'Your data will not be shared',
    OK: 'OK',
    TOTAL_USAGE: 'Total Usage',
    USED: 'used',
    RESEND_INVITE: 'Resend invite?',
    RESEND_INVITE_MESSAGE: 'Are you sure you want to resend an invite to',
    SORRY_SOMETHING_WENT_WRONG: 'Sorry, something went wrong.',
    SORRY_YOU_NEED_TO_UPGRADE: 'Sorry, you need to upgrade your account to create a family.',
    SORRY_INVITE_TOKEN_INVALID: 'Sorry, the invite token seems to be invalid.',
    REVOKE_INVITE: 'Revoke invite?',
    REVOKE_INVITE_MESSAGE: 'Are you sure you want to revoke invite to',
    REVOKE: 'Revoke',
    CANCEL: 'Cancel',
    INVITE_REVOKED: 'Invite revoked',
    REMOVE_MEMBER: 'Remove member?',
    REMOVE_MEMBER_MESSAGE: 'Are you sure you want to remove',
    REMOVE: 'Remove',
    MEMBER_REMOVED: 'Member removed',
    COULD_NOT_FIND_USER: 'Could not find user with that email address',
    PLEASE_ASK_THEM_TO_SIGN_UP: 'Please ask them to sign up @ ente.io',
    REACHED_MAX_FAMILY_SIZE: 'You have reached the maximum number of family members.',
    OOPS_SOMETHING_WENT_WRONG: 'Oops, something went wrong.',
};

export default englishConstants;
